// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina WSDL tool.

import ballerina/data.xmldata;
import ballerina/http;

public isolated client class Client {
    final http:Client clientEp;

    public isolated function init(string serviceUrl = "service/url", *http:CorsConfig config) returns error? {
        self.clientEp = check new ("");
    }
}
