// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina WSDL tool.

import ballerina/data.xmldata;

@xmldata:Namespace {uri: "http://api.foo.com/"}
public type Foo record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    int sequenceGroup;
|};
