/*
 *  Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com)
 *
 *  WSO2 LLC. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

package io.ballerina.projectservice.core;

import java.util.HashMap;
import java.util.Map;

/**
 * Represents the result of a tool execution.
 *
 * @param error       Error message if any occurred during execution.
 * @param textEdits   A map of text edits where keys are file paths and values are the edits to be applied.
 * @param report      HTML report generated by the tool execution.
 *
 * @since 1.2.0
 */
public record ToolExecutionResult(String error, Map<String, String> textEdits, String report) {

    public static class Builder {
        private String error;
        private Map<String, String> textEdits = new HashMap<>();
        private String report;

        public Builder error(String error) {
            this.error = error;
            return this;
        }

        public void textEdits(Map<String, String> textEdits) {
            this.textEdits = textEdits;
        }

        public void report(String report) {
            this.report = report;
        }

        public ToolExecutionResult build() {
            return new ToolExecutionResult(error, textEdits, report);
        }
    }
}