name: PR build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.filter.outputs.build }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            build:
              - 'packages/**'
              - 'submodules/wso2-vscode-extensions/workspaces/common-libs/**'
              - 'common/**'
              - 'rush.json'
              - 'rush-config.json'
              - '.github/workflows/pull-request.yml'
              - '.github/workflows/build.yml'
              - '.github/actions/**'

  build:
    name: Build
    needs: changes
    if: needs.changes.outputs.build == 'true'
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      runOnAWS: ${{ contains(github.event.pull_request.labels.*.name, 'Runner/AWS') }}
      runBalE2ETests: ${{ contains(github.event.pull_request.labels.*.name, 'Checks/Run Ballerina UI Tests') || github.base_ref == 'stable/ballerina' }}
